# Generated by Django 3.2.7 on 2021-09-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file_path', models.FileField(upload_to='documents/papers')),
                ('date_created', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('biology', 'biology'), ('physics', 'physics'), ('chemistry', 'chemistry')], max_length=100)),
            ],
        ),
    ]
